# Github action to build Jekyll site and commit to gh-pages branch
#
#  Built site is pushed to 'gh-pages' branch
#

name: Build Jekyll Site

on:
  push:
    branches: [ main ]

env:
  SRC_DIR: src
  PUBLISH_DIR: gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

    # Checkout default branch into SRC_DIR
    - name: Checkout default branch
      uses: actions/checkout@v2
      with:
        path: ${{env.SRC_DIR}}

    # Checkout existing gh-pages branch into PUBLISH_DIR
    - name: Checkout gh-pages
      uses: actions/checkout@v2
      with:
        path: ${{env.PUBLISH_DIR}}
        ref: 'gh-pages'
    
    # Install ruby 2.7.x
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    # Setup Jekyll in SRC_DIR
    - name: Setup Jekyll
      run: |
        cd ${{env.SRC_DIR}}/doc/site
        sudo gem install bundler jekyll
        bundle update

    # Run Jekyll build and copy output to PUBLISH_DIR
    - name: Build Jekyll Site
      run: |
        cd /${{env.SRC_DIR}}/doc/site
        bundle exec jekyll build
        cp -r _site/* /${{env.PUBLISH_DIR}}/
        touch /${{env.PUBLISH_DIR}}/.nojekyll
        
    # Commit and push changes to remote/gh-pages
    - name: Commit and push to gh-pages
      uses: EndBug/add-and-commit@v4.4.0
      with:
        cwd: ${{env.PUBLISH_DIR}}
        message: "Jekyll build, commit ${{github.sha}} (on:push)"
        ref: 'gh-pages'
      env:  
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}