# Workflow for continuous integration tests
name: Continuous Integration
on: [push, pull_request]

jobs:
  continuous-integration:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        fortran-compiler: [gfortran-8, gfortran-9]
        rte-kernels: [default, openacc]
    env:
      FC: ${{ matrix.fortran-compiler }}
      NCHOME: /usr
      NFHOME: /usr
      # Compiler flags for gfortran 8 and 9.
      FCFLAGS: "-ffree-line-length-none -m64 -std=f2008 -march=native -fbounds-check -finit-real=nan -DUSE_CBOOL"
      RRTMGP_ROOT: ${GITHUB_WORKSPACE}
    # Sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2
    # Set up Python and dependencies
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        python-version: 3.7
    - name: Install python dependencies
      run: conda install --yes urllib3 netcdf4 xarray dask scipy
    # Install FORTRAN compiler and NetCDF libraries
    - name: Install FORTRAN compiler
      run: sudo apt-get install ${{ matrix.fortran-compiler }} libnetcdf-dev
    # NetCDF FORTRAN library
    - name: NetCDF FORTRAN library
      run: |
        git clone https://github.com/Unidata/netcdf-fortran.git --branch v4.4.4
        cd netcdf-fortran
        ./configure --prefix=${NFHOME}
        make
        sudo make install
    - name: Stage RFMIP files
      run: |
        cd ${{RRTMGP_ROOT}}/examples/rfmip-clear-sky
        python ./stage_files.py
        cd ../../
    - name: Make library, examples, tests
      run: |
        export RTE_KERNELS=${{ matrix.rte-kernels }}
        make -C build clean
        make -C build -j 2
        make -C tests clean
        make -C tests -j 1
        make -C examples/all-sky clean
        make -C examples/all-sky -j 2
        export RRTMGP_BUILD=${RRTMGP_ROOT}/build
        make -C examples/rfmip-clear-sky clean
        make -C examples/rfmip-clear-sky -j 2
    - name: Run examples, tests
      run: |
        cd ${RRTMGP_ROOT}/examples/rfmip-clear-sky
        python ./run-rfmip-examples.py --block_size 1800
        cd  ${RRTMGP_ROOT}/examples/all-sky
        python ./run-allsky-example.py
        cd  ${RRTMGP_ROOT}/tests
        cp ${RRTMGP_ROOT}/examples/rfmip-clear-sky/multiple_input4MIPs_radiation_RFMIP_UColorado-RFMIP-1-2_none.nc test_atmospheres.nc
        ./clear_sky_regression test_atmospheres.nc ${RRTMGP_ROOT}/rrtmgp/data/rrtmgp-data-lw-g256-2018-12-04.nc
        ./clear_sky_regression test_atmospheres.nc ${RRTMGP_ROOT}/rrtmgp/data/rrtmgp-data-sw-g224-2018-12-04.nc
    - name: Comparison
      run: |
        cd ${RRTMGP_ROOT}/examples/rfmip-clear-sky
        python ./compare-to-reference.py --fail=7.e-4
        cd ${RRTMGP_ROOT}/examples/all-sky
        python ./compare-to-reference.py
        cd ${RRTMGP_ROOT}/tests
        python verification.py
